Session management
wolox-training/ava-react pull request #25
Opened 2021-01-22 12:48 UTC by 9gustin

## Summary

Add session managment with local storage.
Add session validation on home page.
Add logout to remove session.

## Screenshots

![image](https://user-images.githubusercontent.com/38046239/105492565-e1ea2380-5c96-11eb-80dc-0a7591307aba.png)

## Trello Card

[Session management & Logout](https://trello.com/c/DAEvP3eE/75-session-management-logout)

2021-01-28 14:37 UTC, LucasZibell requested changes

2021-01-28 14:37 UTC, LucasZibell commented on react/w-books/src/app/screens/Home/index.tsx
>  export default function Home() {
export at the end of the file

2021-01-28 14:37 UTC, LucasZibell commented on react/w-books/src/hooks/useSession.ts
> +import { deleteData, getData, saveData, SESSION } from "../utils/manageData";
Use single quotes

2021-01-28 14:37 UTC, LucasZibell commented on react/w-books/src/hooks/useSession.ts
> +  };
```
  const getSession = () => getData(SESSION);
```

2021-01-28 14:37 UTC, LucasZibell commented on react/w-books/src/hooks/useSession.ts
> +  };
```
  const isLogged = (): boolean => getSession();
```

2021-01-28 14:37 UTC, LucasZibell commented on react/w-books/src/hooks/useSession.ts
> +  };
```
  const stopSession = () => deleteData(SESSION);
```

2021-01-28 14:37 UTC, LucasZibell commented on react/w-books/src/hooks/useSession.ts
> +export default useSession;
What logic are you abstracting here... seems you are just renaming functions

2021-01-28 14:37 UTC, LucasZibell commented on react/w-books/src/services/userService.ts
> +    handleAccessToken?.(token);
Check previous PR comments

2021-01-28 14:37 UTC, LucasZibell commented on react/w-books/src/utils/manageData.ts
> +  if (typeof localStorage !== 'undefined') {
When will the LocalStorage be undefined?

2021-01-28 14:37 UTC, LucasZibell commented on react/w-books/src/utils/manageData.ts
> +  if (typeof localStorage !== 'undefined') {
same

2021-01-28 14:37 UTC, LucasZibell commented on react/w-books/src/utils/manageData.ts
> +  if (typeof localStorage !== 'undefined') {
same

2021-01-28 14:37 UTC, LucasZibell commented on react/w-books/src/utils/manageData.ts
> +const saveData = (key: typeof SESSION, value: any) => {
export const

2021-01-28 14:37 UTC, LucasZibell commented on react/w-books/src/utils/manageData.ts
> +const getData = (key: typeof SESSION) => {
export const

2021-01-28 14:37 UTC, LucasZibell commented on react/w-books/src/utils/manageData.ts
> +const deleteData = (key: typeof SESSION) => {
export const

2021-01-29 12:50 UTC, 9gustin commented
changes are ready for review

2021-02-02 17:46 UTC, LucasZibell submitted a review, later dismissed

2021-02-02 17:50 UTC, DavidRojas1612 submitted a review, later dismissed

2021-02-03 21:05 UTC, DavidRojas1612 approved these changes

2021-02-03 21:05 UTC, merged