Add testing to sign up and login form
wolox-training/ava-react pull request #26
Opened 2021-01-22 17:46 UTC by 9gustin

## Summary

Add testing to sign up form.
Add testing to login form

## Screenshots

-

## Trello Card

[Tests de login](https://trello.com/c/5niBr3DE/114-tests-de-login)

2021-01-28 14:41 UTC, LucasZibell requested changes

2021-01-28 14:41 UTC, LucasZibell commented on react/w-books/src/app/screens/Login/components/LoginForm/index.test.tsx
> +  email: 'agustin.vazquez@wolox.com.ar',
Don't use personal information

2021-01-28 14:41 UTC, LucasZibell commented on react/w-books/src/app/screens/Login/components/LoginForm/index.test.tsx
> +  email: '********$%a#@wolox.com.ar',
same, use mocked data

2021-01-28 14:41 UTC, LucasZibell commented on react/w-books/src/app/screens/SignUp/components/SignUpForm/index.test.tsx
> +}
EOF

2021-01-28 14:41 UTC, LucasZibell commented on react/w-books/src/app/screens/SignUp/components/SignUpForm/index.test.tsx
> +  }
Don't use personal information on the test

2021-01-28 14:41 UTC, LucasZibell commented on react/w-books/src/app/screens/Login/components/LoginForm/index.test.tsx
> +}
EOF

2021-01-29 14:25 UTC, 9gustin commented
changes are ready for review

2021-02-02 14:09 UTC, DavidRojas1612 approved these changes

2021-02-02 17:46 UTC, LucasZibell approved these changes

2021-02-03 21:04 UTC, merged