Add books list view
wolox-training/ava-react pull request #28
Opened 2021-01-25 15:24 UTC by 9gustin

## Summary

Add books list view.
Add service to get books from API.

## Screenshots

![image](https://user-images.githubusercontent.com/38046239/105725381-a7d38880-5f07-11eb-9ebd-dd96f5fd2735.png)

## Trello Card

[Book List & Auth header](https://trello.com/c/oop2ep1C/77-book-list-auth-header)

2021-01-28 19:39 UTC, LucasZibell requested changes

2021-01-28 19:39 UTC, LucasZibell commented on react/w-books/src/app/screens/Home/utils.ts
> +    title: book.title,
`...book`

2021-01-28 19:39 UTC, LucasZibell commented on react/w-books/src/app/screens/Home/utils.ts
> +    props: [
This name seems a little bit off. Let's look for a better name

2021-01-28 19:39 UTC, LucasZibell commented on react/w-books/src/hooks/useSession.ts
>    };
```
  const startSession = (session: Session) => saveData(SESSION, session)
```

2021-01-29 15:22 UTC, 9gustin commented
I made changes. The purpose of the getSession and setSession api functions is to encapsulate the auth. Only the api configuration knows how to get the authentication of a response (in this case take 3 headers) and the setSession knows how to put the authentication in the request. If sometime a header is added, we modify it there and not in each endpoint method

2021-02-02 14:32 UTC, DavidRojas1612 requested changes

2021-02-02 14:32 UTC, DavidRojas1612 commented on react/w-books/src/app/components/Card/index.tsx
> +    <a className={
use anchor only to external links, instead of use Link component of the react router

2021-02-02 14:32 UTC, DavidRojas1612 commented on react/w-books/src/app/components/CardProp/index.tsx
> +function CardProp({ className, propName, value, isSimple, keepVisibleSimple }: CardPropProps) {
CardProp? 👀  CardPropProps?

2021-02-02 14:32 UTC, DavidRojas1612 commented on react/w-books/src/app/components/Routes/components/PrivateRoute/index.tsx
> +        hasData(SESSION) ? <Component {...props} /> : <Redirect to={PATHS.login} />
See the comments of the Private and public router

2021-02-02 17:55 UTC, DavidRojas1612 approved these changes

2021-02-03 21:03 UTC, merged