Convert loading component to HOC
wolox-training/ava-react pull request #30
Opened 2021-01-26 14:59 UTC by 9gustin

## Summary

Convert loading component to HOC

## Screenshots

-

## Trello Card

[Patterns II - HOCs](https://trello.com/c/WohsDPH5/52-patterns-ii-hocs)

2021-01-28 19:42 UTC, LucasZibell requested changes

2021-01-28 19:42 UTC, LucasZibell commented on react/w-books/src/app/components/Loading/index.tsx
> +      </svg>
This should be a svg file

2021-01-28 19:42 UTC, LucasZibell commented on react/w-books/src/app/screens/Book/index.tsx
> +          })
Use it as a hook, not inside the component

2021-01-28 19:42 UTC, LucasZibell commented on react/w-books/src/app/screens/Home/index.tsx
> +        })
same

2021-01-28 19:42 UTC, LucasZibell commented on react/w-books/src/app/screens/Login/components/LoginForm/index.tsx
> +          })
same

2021-01-28 19:42 UTC, LucasZibell commented on react/w-books/src/app/screens/SignUp/components/SignUpForm/index.tsx
> +          })
same

2021-01-28 19:42 UTC, LucasZibell commented on react/w-books/src/utils/bookToCard.ts
> +  }:{};
check eslint

2021-01-29 17:44 UTC, 9gustin commented
changes are ready for review

2021-02-03 20:54 UTC, DavidRojas1612 approved these changes

2021-02-03 21:02 UTC, merged